flags: {}
packages:
- '.'
- lib/theory/
- lib/term/
- lib/utils/
- lib/sapic/
- lib/export/
- lib/accountability/
- lib/rule-translation/
resolver: lts-19.32
ghc-options:
  "$everything": -Wall
nix:
  packages: [ zlib ]
