flags: {}
packages:
- '.'
- lib/theory/
- lib/term/
- lib/utils/
- lib/sapic/
- lib/export/
- lib/accountability/
resolver: nightly-2022-06-01
ghc-options:
  "$everything": -Wall
nix:
  packages: [ zlib ]
