#!/bin/bash

set -x # print what we do
temp=$(mktemp -d)/$(basename "$1")

tamarin-prover "$1" -m=proverif > "$temp.gs" && echo "$temp.gs" && gsverif -o "$temp.pv" "$temp.gs" && proverif "$temp.pv"
#requires gsverif 2.0, i.e. the new version made by Vincent with assumeCell tag
