#!/usr/bin/env python3
#oracle_RF
import re
import os
import sys

debug = False

lines = sys.stdin.readlines()

lemma = sys.argv[1]
if debug: print("Lemma is "+lemma, file=sys.stderr)

priorities = []

def prioritize(num,m):
  global priorities, plist, match
  for i in range(len(priorities)):
    if match:
      if re.match(priorities[i],m):
         plist[i].append(num)
         break
    else:
      if priorities[i] in m:
         plist[i].append(num)
         break

if lemma == "indivVerif_D_ps": 
  match = False
  priorities = ["~~","In_S","!KU( ~lsk","!KU( ~skS","!KU( ~x","AgSt","In_A","'zkp'","encp(","!KD","Out_A","In_A"]

if lemma == "indivVerif_D_sel": 
  match = False
  priorities = ["~~","In_S","!KU( ~lsk","!KU( ~skS","!KU( ~x","AgSt","In_A","'zkp'","encp(","!KD","Out_A","In_A"]

if lemma == "Observational_equivalence": 
  match = False
  priorities = ["Out_A","~~","In_A","In_S","!KU( ~lsk"," pk(~lskD1)"," pk(~lskDa)"," pk(~lskDb)","!KU( ~x","AgSt","In_A","encp(","!KD","Out_A","In_A"]

#j
plist = [ [] for i in priorities ]

for line in lines:
  if debug: print("Line is "+line, end=' ', file=sys.stderr)

  num = line.split(':')[0]

#  if lemma == "secret":
  prioritize(num,line)
#    if debug: print >> sys.stderr, "Current list: ",plist
#  else:
#    sys.exit(0)

for j in range(len(plist)):
  for i in plist[j]:
    print(i)
#print 1
